
export const popularMovies = [
    {
      Title: "The Shawshank Redemption",
      Year: "1994",
      imdbRating: "9.3",
      Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWTn2eHe9wk096HG-UWxrM1VtQr99LFyFe0g&s",
      Genre: "Drama",
      runtime: "142 min",
      director: "Frank Darabont",
      imdbID: "tt0111161",
    },
    {
        Title: "Inception",
    Year: "2010",
    imdbRating: "8.8",
    Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmkq35zEZtIgZWAHKWdGD_IRMUx-c9EOgrcQ&s",
    Genre: "Action, Adventure, Sci-Fi",
    runtime: "148 min",
    director: "Christopher Nolan",
    imdbID: "tt1375666",
    },

   
  
   
    {
        Title: "Interstellar",
        Year: "2014",
        imdbRating: "8.6",
        Poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg",
        Genre: "Adventure, Drama, Sci-Fi",
        runtime: "169 min",
        director: "Christopher Nolan",
        imdbID: "tt0816692",
    },
    {
        Title: "The Dark Knight",
        Year: "2008",
        imdbRating: "9.0",
        Poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
        Genre: "Action, Crime, Drama",
        runtime: "152 min",
        director: "Christopher Nolan",
        imdbID: "tt0468569",
      },
    {
      Title: "The Lord of the Rings: The Return of the King",
      Year: "2003",
      imdbRating: "8.9",
      Poster: "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_.jpg",
      Genre: "Action, Adventure, Drama",
      runtime: "201 min",
      director: "Peter Jackson",
      imdbID: "tt0167260",
    },
    {
        Title: "Shell Island",
    Year: "2023",
    imdbRating: "N/A",
    Poster: "https://pixel.disco.skyshowtime.com/uuid/00afb860-ffcc-3028-a07e-84c2c80f21b0/COVER_TITLE_TALL?language=sv-SE&proposition=SKYSHOWTIME&version=7123aa2d-4ac1-3880-9216-06ef2e51f192",
    Genre: "Drama, Short",
    runtime: "15 min",
    director: "Joe Simmons",
    imdbID: "N/A",
    },
    {
      Title: "Fight Club",
      Year: "1999",
      imdbRating: "8.8",
      Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE5rkKTG2JFWq_FiFZnIkDhQ_ZPqYAPHYqAw&s",
      Genre: "Drama",
      runtime: "139 min",
      director: "David Fincher",
      imdbID: "tt0137523",
    },
    {
      Title: "Forrest Gump",
      Year: "1994",
      imdbRating: "8.8",
      Poster: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      Genre: "Drama, Romance",
      runtime: "142 min",
      director: "Robert Zemeckis",
      imdbID: "tt0109830",
    },
    {
        Title: "The Godfather",
        Year: "1972",
        imdbRating: "9.2",
        Poster: "https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_.jpg",
        Genre: "Crime, Drama",
        runtime: "175 min",
        director: "Francis Ford Coppola",
        imdbID: "tt0068646",
      },
      {
        Title: "Parasite",
    Year: "2019",
    imdbRating: "8.6",
    Poster: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    Genre: "Comedy, Drama, Thriller",
    runtime: "132 min",
    director: "Bong Joon Ho",
    imdbID: "tt6751668",
    },
  ];
  
  export const popularSeries = [
    {
      Title: "Breaking Bad",
      Year: "2008–2013",
      imdbRating: "9.5",
      Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhGRPHbiT9WRbp4Mc7kKgT6LHSPHrDiWfEg&s",
      Genre: "Crime, Drama, Thriller",
      runtime: "49 min",
      seasons: 5,
      imdbID: "tt0903747",
    },
    {
      Title: "Game of Thrones",
      Year: "2011–2019",
      imdbRating: "9.3",
      Poster: "https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_.jpg",
      Genre: "Action, Adventure, Drama",
      runtime: "57 min",
      seasons: 8,
      imdbID: "tt0944947",
    },
    {
      Title: "The Wire",
      Year: "2002–2008",
      imdbRating: "9.3",
      Poster: "https://m.media-amazon.com/images/M/MV5BNGQ0ZjBlOGItZGY4MC00MzExLWJkNGYtZmUxYzg1NTgyNDVlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      Genre: "Crime, Drama, Thriller",
      runtime: "59 min",
      seasons: 5,
      imdbID: "tt0306414",
    },
    {
        Title: "Prison Break",
        Year: "2005–2017",
        imdbRating: 8.3,
        Genre: "Action, Crime, Drama",
        runtime: "44 min per episode",
        seasons: 5,
        imdbID: "tt0455275",
        Poster: "https://upload.wikimedia.org/wikipedia/en/4/46/Prison_Break_season_1_dvd.jpg"
      },
    {
      Title: "The Mandalorian",
      Year: "2019–",
      imdbRating: "8.8",
      Poster: "https://m.media-amazon.com/images/M/MV5BNjgxZGM0OWUtZGY1MS00MWRmLTk2N2ItYjQyZTI1OThlZDliXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      Genre: "Action, Adventure, Fantasy",
      runtime: "35 min",
      seasons: 3,
      imdbID: "tt8111088",
    },
    {
        Title: "Peaky Blinders",
        Year: "2013–2022",
        imdbRating: 8.8,
        Genre: "Crime, Drama",
        runtime: "60 min per episode",
        seasons: 6,
        imdbID: "tt2442560",
        Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbM0o4ann06FnKegan29A60vjrv3S-JpNxpA&s"
    },
    
        {
            Title: "The Blacklist",
            Year: "2013–2023",
            imdbRating: 8.0,
            Genre: "Crime, Drama, Mystery",
            runtime: "43 min per episode",
            director: "Jon Bokenkamp",
            imdbID: "tt2741602",
            Poster: "https://m.media-amazon.com/images/M/MV5BNDk4MGU4NTItNDMyMC00NjQ0LWFlMWUtYzJlMTM1M2M2ZTU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
          },
    
    {
      Title: "Friends",
      Year: "1994–2004",
      imdbRating: "8.9",
      Poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJLjWydqPvMg0WZ45kCqimdGO99o6_hMGP_w&s",
      Genre: "Comedy, Romance",
      runtime: "22 min",
      seasons: 10,
      imdbID: "tt0108778",
    },
    {
      Title: "The Office",
      Year: "2005–2013",
      imdbRating: "8.9",
      Poster: "https://m.media-amazon.com/images/M/MV5BZjQwYzBlYzUtZjhhOS00ZDQ0LWE0NzAtYTk4MjgzZTNkZWEzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      Genre: "Comedy",
      runtime: "22 min",
      seasons: 9,
      imdbID: "tt0386676",
    },
    {
      Title: "True Detective",
      Year: "2014–",
      imdbRating: "8.9",
      Poster: "https://m.media-amazon.com/images/M/MV5BNzk4ODZkNTYtNjU2Yi00YTU5LWFmMjYtNjNiMTRhMjEzNDQ1XkEyXkFqcGc@._V1_QL75_UY281_CR4,0,190,281_.jpg ",
      Genre: "Crime, Drama, Mystery",
      runtime: "55 min",
      seasons: 3,
      imdbID: "tt2356777",
    },
  ];
  